# This is a basic workflow to help you get started with Actions

name: Pre-Release tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  pull_request:
    branches: [ "pre-release" ]
  push:
    branches: [ "pre-release" ]

jobs:
  test-feature:
    runs-on: macOS-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests with Gradle
        run: ./gradlew app:testDebugUnitTest
  
